### ISSUE TITLE
Encrypt all CI passwords with dblock's AppVeyor secret

### ISSUE THREAD

**Issue by dblock** [dblock/log4jna#23]
I would like CI to work the same way for any fork without effort, and have clear instructions how to set it up. This probably means extracting a secret out of the appveyor.yml, and removing hard-coded values for Sonatype username/password push and such.

@claudiow  ^^^ thanks ;)

**Comment by claudiow** [comment]
That is impossible if you want to deploy to Maven Central from CI with one click. 

Maven requires those passwords to work as it will require a password for GitHub to TAG and check in the tag during a release  otherwise you will have to build and deploy the releases in your local machine.

Actually CI and shared `settings.xml` where the main use-case drivers for maven to add password encryption support. I think that my mistake is that we do not need to distribute the settings-security.xml that allows users to create and change passwords in settings.xml.

See [https://maven.apache.org/guides/mini/guide-encryption.html](https://maven.apache.org/guides/mini/guide-encryption.html) and [http://blog.sonatype.com/2009/10/maven-tips-and-tricks-encrypting-passwords/](http://blog.sonatype.com/2009/10/maven-tips-and-tricks-encrypting-passwords/) even JBoss OS project uses this approach see [https://developer.jboss.org/wiki/Mavensettingsxmlmaskingpassword](https://developer.jboss.org/wiki/Mavensettingsxmlmaskingpassword)

I created the user Log4JNACI to be used on CI, this is what I will be using in CI going further without the settings-security.xml file.

The settings.xml file will be encrypted with the AppVeyor secret what we are using.

In the future when I delete my own instance from AppVeyor the secret will stop being an annoyance, This is happening because I have to test the build process in my own instance because I have to grab the changes from my fork before merging.

Once all this testing is done we will have only your project in AppVeyor and you can forget about the passwords and secret as they are going to be fixed.

Unfortunately there is no other way that I'm aware to pass passwords to Maven.

**Comment by dblock** [comment]
That all makes sense. Maybe you can do what you suggest sooner to cleanup things - instead of using your own AppVeyor account, make pull requests that get automatically built by my AppVeyor account, even before those pull requests are ready to be merged? I don't look at anything that's not passing build anyway :)

**Comment by dblock** [comment]
I renamed this to _Encrypt all CI passwords with dblock's AppVeyor secret_ I think it reflects the long range workitem.

**Comment by claudiow** [comment]
Here is my concern with that. 

All the mess with Git and the myriad of commits comes from the need of do a lot of trial and error.
I might commit every minute when testing something that does not work as expect, 
I need to echo stuff to the console and delete the echo once it works
My working branch maven-conversion had over 200 commits in a week to create appveyor.yml

I don't see this getting better going forward it rather will worsen as the release:plugin + Sonatype requirements requires a lot of testing.

What about this: I have access to your repository from my Appveyor project, it looks that you grant me access in GitHub 

I create a project that builds your master [https://ci.appveyor.com/project/claudiow/log4jna-7o8kf](https://ci.appveyor.com/project/claudiow/log4jna-7o8kf). We can go with this build until we are ready.

**Comment by dblock** [comment]
That totally fine, whatever works.

Do note that once you made a pull request, when you `--amend` and then push, build picks it up immediately. So it's not uncommon to be making hundreds of changes and such.

**Comment by claudiow** [comment]
This is done too, you have the secret and can use it, do you want to close i or wait until the Appveyor release works?

**Comment by dblock** [comment]
Lets close this.
